webtalk_init -webtalk_dir C:/Users/hn/Desktop/DFDP1100_2020_Projects/Demo_01/Demo_01.sim/sim_1/behav/xsim.dir/one_bit_comparator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 13 11:01:09 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4621c317-7e27-48e3-90c0-565aee0f8ec9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bf738bb84399481c8f79c553d248d468" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6528_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1674074928 -regid "" -xml C:/Users/hn/Desktop/DFDP1100_2020_Projects/Demo_01/Demo_01.sim/sim_1/behav/xsim.dir/one_bit_comparator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hn/Desktop/DFDP1100_2020_Projects/Demo_01/Demo_01.sim/sim_1/behav/xsim.dir/one_bit_comparator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hn/Desktop/DFDP1100_2020_Projects/Demo_01/Demo_01.sim/sim_1/behav/xsim.dir/one_bit_comparator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
